---
title: "OER Attribution Information"
---

## Chapter 1

Parts of the Introduction "African Virtual University" by John T. Phiri is licensed under CC BY 2.5

Throughout Chapter "Psyc 200 Lifespan Psychology" by Laura Overstreet is licensed under CC BY 3.0

Parts of Theorists and Research Methods "Introduction to Psychology \[Adapted from Charles Stangor, Introduction to Psychology\]" by Martha Lally and Suzanne Valentine-French is licensed under CC BY 3.0 / A derivative from the original work

## Chapter 2

Throughout Chapter "Psyc 200 Lifespan Psychology" by Laura Overstreet is licensed under CC BY 3.0

## Chapter 3

Throughout Chapter "Psyc 200 Lifespan Psychology" by Laura Overstreet is licensed under CC BY 3.0

Parts of Language Section "Introduction to Psychology \[Adapted from Charles Stangor, Introduction to Psychology\]" by Martha Lally and Suzanne Valentine-French is licensed under CC BY 3.0 / A derivative from the original work

Parts of Parenting "The Developing Parent" by NOBA is licensed under CC BY 3.0\

## Chapter 4

Throughout Chapter "Psyc 200 Lifespan Psychology" by Laura Overstreet is licensed under CC BY 3.0

Theory of Mind "Theory of Mind" by NOBA is licensed under CC BY 4.0

## Chapter 5

Throughout Chapter "Psyc 200 Lifespan Psychology" by Laura Overstreet is licensed under CC BY 3.0

Education Topics "Educational Psychology" by Kelvin Seifert is licensed under CC BY 3.0

Intelligence and Moral Development "Introduction to Psychology \[Adapted from Charles Stangor, Introduction to Psychology\]" by Martha Lally and Suzanne Valentine-French is licensed under CC BY 3.0 / A derivative from the original work

## Chapter 6

Peers and Romantic Relationships "Adolescent Development" by NOBA is licensed under CC BY 3.0

## Chapter 7

Sexual Responsiveness Peak, Friendships, Love, and Tacit Knowledge "Psyc 200 Lifespan Psychology" by Laura Overstreet is licensed under CC BY 3.0

Parenthood "The Developing Parent" by NOBA is licensed under CC BY 3.0

## Chapter 8

Mechanics of Cognition, Aspects of Midlife Crisis, and Aspects of Family Relationships "Psyc 200 Lifespan Psychology" by Laura Overstreet is licensed under CC BY 3.0

Intelligence "Introduction to Psychology \[Adapted from Charles Stangor, Introduction to Psychology\]" by Martha Lally and Suzanne Valentine-French is licensed under CC BY 3.0 / A derivative from the original work

Aspects of Physical Aging "Psychology" by Boundless is licensed under CC BY 3.0

Stress "The Healthy Life" by NOBA is licensed under CC BY-SA 3.0

Friendship "Love, Friendship and Social Support" by NOBA is licensed under CC BY 3.0

## Chapter 9

Aspects of Aging, "Psyc 200 Lifespan Psychology" by Laura Overstreet is licensed under CC BY 3.0

Successful Aging and Social Networks "Aging" by NOBA is licensed under CC BY 3.0

## Chapter 10

Aspects of Death, Kübler-Ross Model, and Anticipatory Grief "Psyc 200 Lifespan Psychology" by Laura Overstreet is licensed under CC BY 3.0
